/** Generated by itemis CREATE code generator. */


#include "../src/sc_types.h"

#include "Statechart.h"
#include "Statechart_required.h"

/*! \file
Implementation of the state machine 'Statechart'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enact_main_region_ADC_r1_SampleRequestedADC(Statechart* handle);
static void enact_main_region_ADC_r1_SampleReadingADC(Statechart* handle);
static void enact_main_region_ADC_r1_DisplayData(Statechart* handle);
static void enact_main_region_ADC_r1_UsartTransmit_ADC(Statechart* handle);
static void enact_main_region_ADC_r1_Tarpinis_RMS(Statechart* handle);
static void enact_main_region_ADC_r1_ProcessData_ADC(Statechart* handle);
static void enact_main_region_I2C_r2_DisplayData(Statechart* handle);
static void enact_main_region_I2C_r2_UsartTransmit_I2C(Statechart* handle);
static void enact_main_region_I2C_r2_ProcessData_I2C(Statechart* handle);
static void enact_main_region_I2C_r2_ReadI2C(Statechart* handle);
static void exact_main_region_ADC_r1_SampleReadingADC(Statechart* handle);
static void exact_main_region_ADC_r1_DisplayData(Statechart* handle);
static void exact_main_region_ADC_r1_UsartTransmit_ADC(Statechart* handle);
static void exact_main_region_ADC_r1_Tarpinis_RMS(Statechart* handle);
static void exact_main_region_ADC_r1_ProcessData_ADC(Statechart* handle);
static void exact_main_region_I2C_r2_DisplayData(Statechart* handle);
static void exact_main_region_I2C_r2_UsartTransmit_I2C(Statechart* handle);
static void exact_main_region_I2C_r2_ProcessData_I2C(Statechart* handle);
static void enseq_main_region_ADC_default(Statechart* handle);
static void enseq_main_region_ADC_r1_WaitSamplePeriod_default(Statechart* handle);
static void enseq_main_region_ADC_r1_SampleRequestedADC_default(Statechart* handle);
static void enseq_main_region_ADC_r1_SampleReadingADC_default(Statechart* handle);
static void enseq_main_region_ADC_r1_DisplayData_default(Statechart* handle);
static void enseq_main_region_ADC_r1_Tarpinis_RMS_default(Statechart* handle);
static void enseq_main_region_ADC_r1_ProcessData_ADC_default(Statechart* handle);
static void enseq_main_region_I2C_default(Statechart* handle);
static void enseq_main_region_I2C_r2_WaitSamplePeriod_default(Statechart* handle);
static void enseq_main_region_I2C_r2_DisplayData_default(Statechart* handle);
static void enseq_main_region_I2C_r2_ProcessData_I2C_default(Statechart* handle);
static void enseq_main_region_I2C_r2_ReadI2C_default(Statechart* handle);
static void enseq_main_region_default(Statechart* handle);
static void enseq_main_region_ADC_r1_default(Statechart* handle);
static void enseq_main_region_I2C_r2_default(Statechart* handle);
static void exseq_main_region_ADC(Statechart* handle);
static void exseq_main_region_ADC_r1_WaitSamplePeriod(Statechart* handle);
static void exseq_main_region_ADC_r1_SampleRequestedADC(Statechart* handle);
static void exseq_main_region_ADC_r1_SampleReadingADC(Statechart* handle);
static void exseq_main_region_ADC_r1_DisplayData(Statechart* handle);
static void exseq_main_region_ADC_r1_UsartTransmit_ADC(Statechart* handle);
static void exseq_main_region_ADC_r1_Tarpinis_RMS(Statechart* handle);
static void exseq_main_region_ADC_r1_ProcessData_ADC(Statechart* handle);
static void exseq_main_region_I2C(Statechart* handle);
static void exseq_main_region_I2C_r2_WaitSamplePeriod(Statechart* handle);
static void exseq_main_region_I2C_r2_DisplayData(Statechart* handle);
static void exseq_main_region_I2C_r2_UsartTransmit_I2C(Statechart* handle);
static void exseq_main_region_I2C_r2_ProcessData_I2C(Statechart* handle);
static void exseq_main_region_I2C_r2_ReadI2C(Statechart* handle);
static void exseq_main_region(Statechart* handle);
static void exseq_main_region_ADC_r1(Statechart* handle);
static void exseq_main_region_I2C_r2(Statechart* handle);
static void react_main_region__entry_Default(Statechart* handle);
static void react_main_region_ADC_r1__entry_Default(Statechart* handle);
static void react_main_region_I2C_r2__entry_Default(Statechart* handle);

/*! State machine reactions. */
static sc_integer react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state ADC. */
static sc_integer main_region_ADC_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state WaitSamplePeriod. */
static sc_integer main_region_ADC_r1_WaitSamplePeriod_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state SampleRequestedADC. */
static sc_integer main_region_ADC_r1_SampleRequestedADC_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state SampleReadingADC. */
static sc_integer main_region_ADC_r1_SampleReadingADC_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state DisplayData. */
static sc_integer main_region_ADC_r1_DisplayData_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state UsartTransmit_ADC. */
static sc_integer main_region_ADC_r1_UsartTransmit_ADC_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Tarpinis_RMS. */
static sc_integer main_region_ADC_r1_Tarpinis_RMS_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state ProcessData_ADC. */
static sc_integer main_region_ADC_r1_ProcessData_ADC_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state I2C. */
static sc_integer main_region_I2C_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state WaitSamplePeriod. */
static sc_integer main_region_I2C_r2_WaitSamplePeriod_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state DisplayData. */
static sc_integer main_region_I2C_r2_DisplayData_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state UsartTransmit_I2C. */
static sc_integer main_region_I2C_r2_UsartTransmit_I2C_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state ProcessData_I2C. */
static sc_integer main_region_I2C_r2_ProcessData_I2C_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state ReadI2C. */
static sc_integer main_region_I2C_r2_ReadI2C_react(Statechart* handle, const sc_integer transitioned_before);


static void clear_in_events(Statechart* handle);

static void micro_step(Statechart* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Statechart* handle);




static void statechart_internal_set_sample_no(Statechart* handle, sc_integer value)
;
static void statechart_internal_set_sample1_no(Statechart* handle, sc_integer value)
;
static void statechart_internal_set_n_ADC(Statechart* handle, sc_integer value)
;
static void statechart_internal_set_sample_i2c(Statechart* handle, sc_integer value)
;
static void statechart_internal_set_n_I2C(Statechart* handle, sc_integer value)
;


static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity);
static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq);
static void statechart_event_init(statechart_event * ev, StatechartEventID name);
static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq);
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev);
static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name);
static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event);
static statechart_event statechart_get_next_event(Statechart* handle);
static sc_boolean statechart_dispatch_next_event(Statechart* handle);


void statechart_init(Statechart* handle)
{
	sc_integer i;
	
	for (i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Statechart_last_state;
	}
	
				
	clear_in_events(handle);
	
	
	/* Default init sequence for statechart Statechart */
	statechart_internal_set_sample_no(handle, 0);
	statechart_internal_set_sample1_no(handle, 0);
	statechart_internal_set_n_ADC(handle, 0);
	statechart_internal_set_sample_i2c(handle, 0);
	statechart_internal_set_n_I2C(handle, 0);
	
	handle->isExecuting = bool_false;
	statechart_eventqueue_init(&handle->in_event_queue, handle->in_buffer, STATECHART_IN_EVENTQUEUE_BUFFERSIZE);
}

void statechart_enter(Statechart* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart Statechart */
	enseq_main_region_default(handle);
	handle->doCompletion = bool_false;
	do
	{ 
		if (handle->completed == bool_true)
		{ 
			handle->doCompletion = bool_true;
		} 
		handle->completed = bool_false;
		micro_step(handle);
		handle->doCompletion = bool_false;
	} while (handle->completed == bool_true);
	handle->isExecuting = bool_false;
}

void statechart_exit(Statechart* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart Statechart */
	exseq_main_region(handle);
	handle->isExecuting = bool_false;
}

/*!
Can be used by the client code to trigger a run to completion step without raising an event.
*/
void statechart_trigger_without_event(Statechart* handle) {
	run_cycle(handle);
}


sc_boolean statechart_is_active(const Statechart* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Statechart_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean statechart_is_final(const Statechart* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Statechart_main_region_ADC :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_ADC] >= Statechart_main_region_ADC
				&& handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_ADC] <= Statechart_main_region_ADC_r1_ProcessData_ADC);
				break;
		case Statechart_main_region_ADC_r1_WaitSamplePeriod :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_ADC_R1_WAITSAMPLEPERIOD] == Statechart_main_region_ADC_r1_WaitSamplePeriod
			);
				break;
		case Statechart_main_region_ADC_r1_SampleRequestedADC :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_ADC_R1_SAMPLEREQUESTEDADC] == Statechart_main_region_ADC_r1_SampleRequestedADC
			);
				break;
		case Statechart_main_region_ADC_r1_SampleReadingADC :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_ADC_R1_SAMPLEREADINGADC] == Statechart_main_region_ADC_r1_SampleReadingADC
			);
				break;
		case Statechart_main_region_ADC_r1_DisplayData :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_ADC_R1_DISPLAYDATA] == Statechart_main_region_ADC_r1_DisplayData
			);
				break;
		case Statechart_main_region_ADC_r1_UsartTransmit_ADC :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_ADC_R1_USARTTRANSMIT_ADC] == Statechart_main_region_ADC_r1_UsartTransmit_ADC
			);
				break;
		case Statechart_main_region_ADC_r1_Tarpinis_RMS :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_ADC_R1_TARPINIS_RMS] == Statechart_main_region_ADC_r1_Tarpinis_RMS
			);
				break;
		case Statechart_main_region_ADC_r1_ProcessData_ADC :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_ADC_R1_PROCESSDATA_ADC] == Statechart_main_region_ADC_r1_ProcessData_ADC
			);
				break;
		case Statechart_main_region_I2C :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_I2C] >= Statechart_main_region_I2C
				&& handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_I2C] <= Statechart_main_region_I2C_r2_ReadI2C);
				break;
		case Statechart_main_region_I2C_r2_WaitSamplePeriod :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_I2C_R2_WAITSAMPLEPERIOD] == Statechart_main_region_I2C_r2_WaitSamplePeriod
			);
				break;
		case Statechart_main_region_I2C_r2_DisplayData :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_I2C_R2_DISPLAYDATA] == Statechart_main_region_I2C_r2_DisplayData
			);
				break;
		case Statechart_main_region_I2C_r2_UsartTransmit_I2C :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_I2C_R2_USARTTRANSMIT_I2C] == Statechart_main_region_I2C_r2_UsartTransmit_I2C
			);
				break;
		case Statechart_main_region_I2C_r2_ProcessData_I2C :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_I2C_R2_PROCESSDATA_I2C] == Statechart_main_region_I2C_r2_ProcessData_I2C
			);
				break;
		case Statechart_main_region_I2C_r2_ReadI2C :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_I2C_R2_READI2C] == Statechart_main_region_I2C_r2_ReadI2C
			);
				break;
			default:
				result = bool_false;
				break;
		}
		return result;
	}

static void clear_in_events(Statechart* handle)
{
	handle->iface.Ev_GetSample_raised = bool_false;
	handle->iface.Ev_ADCSampleReady_raised = bool_false;
	handle->iface.Ev_GetSample_i2c_raised = bool_false;
	handle->iface.ButtonPush_raised = bool_false;
}

static void micro_step(Statechart* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_ADC_r1_WaitSamplePeriod :
		{
			main_region_ADC_r1_WaitSamplePeriod_react(handle,-1);
			break;
		}
		case Statechart_main_region_ADC_r1_SampleRequestedADC :
		{
			main_region_ADC_r1_SampleRequestedADC_react(handle,-1);
			break;
		}
		case Statechart_main_region_ADC_r1_SampleReadingADC :
		{
			main_region_ADC_r1_SampleReadingADC_react(handle,-1);
			break;
		}
		case Statechart_main_region_ADC_r1_DisplayData :
		{
			main_region_ADC_r1_DisplayData_react(handle,-1);
			break;
		}
		case Statechart_main_region_ADC_r1_UsartTransmit_ADC :
		{
			main_region_ADC_r1_UsartTransmit_ADC_react(handle,-1);
			break;
		}
		case Statechart_main_region_ADC_r1_Tarpinis_RMS :
		{
			main_region_ADC_r1_Tarpinis_RMS_react(handle,-1);
			break;
		}
		case Statechart_main_region_ADC_r1_ProcessData_ADC :
		{
			main_region_ADC_r1_ProcessData_ADC_react(handle,-1);
			break;
		}
		case Statechart_main_region_I2C_r2_WaitSamplePeriod :
		{
			main_region_I2C_r2_WaitSamplePeriod_react(handle,-1);
			break;
		}
		case Statechart_main_region_I2C_r2_DisplayData :
		{
			main_region_I2C_r2_DisplayData_react(handle,-1);
			break;
		}
		case Statechart_main_region_I2C_r2_UsartTransmit_I2C :
		{
			main_region_I2C_r2_UsartTransmit_I2C_react(handle,-1);
			break;
		}
		case Statechart_main_region_I2C_r2_ProcessData_I2C :
		{
			main_region_I2C_r2_ProcessData_I2C_react(handle,-1);
			break;
		}
		case Statechart_main_region_I2C_r2_ReadI2C :
		{
			main_region_I2C_r2_ReadI2C_react(handle,-1);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

static void run_cycle(Statechart* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	statechart_dispatch_next_event(handle);
	do
	{ 
		handle->doCompletion = bool_false;
		do
		{ 
			if (handle->completed == bool_true)
			{ 
				handle->doCompletion = bool_true;
			} 
			handle->completed = bool_false;
			micro_step(handle);
			handle->doCompletion = bool_false;
		} while (handle->completed == bool_true);
		clear_in_events(handle);
	} while (statechart_dispatch_next_event(handle) == bool_true);
	handle->isExecuting = bool_false;
}


void statechart_raise_ev_GetSample(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_Ev_GetSample);
	run_cycle(handle);
}

void statechart_raise_ev_ADCSampleReady(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_Ev_ADCSampleReady);
	run_cycle(handle);
}

void statechart_raise_ev_GetSample_i2c(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_Ev_GetSample_i2c);
	run_cycle(handle);
}

void statechart_raise_buttonPush(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_ButtonPush);
	run_cycle(handle);
}




static void statechart_internal_set_sample_no(Statechart* handle, sc_integer value)
{
	handle->internal.sample_no = value;
}
static void statechart_internal_set_sample1_no(Statechart* handle, sc_integer value)
{
	handle->internal.sample1_no = value;
}
static void statechart_internal_set_n_ADC(Statechart* handle, sc_integer value)
{
	handle->internal.N_ADC = value;
}
static void statechart_internal_set_sample_i2c(Statechart* handle, sc_integer value)
{
	handle->internal.sample_i2c = value;
}
static void statechart_internal_set_n_I2C(Statechart* handle, sc_integer value)
{
	handle->internal.N_I2C = value;
}


/* implementations of all internal functions */

/* Entry action for state 'SampleRequestedADC'. */
static void enact_main_region_ADC_r1_SampleRequestedADC(Statechart* handle)
{
	/* Entry action for state 'SampleRequestedADC'. */
	statechart_startConvADC(handle);
}

static void enact_main_region_ADC_r1_SampleReadingADC(Statechart* handle)
{
	/* Entry action for state 'SampleReadingADC'. */
	statechart_readADCSample(handle);
	handle->completed = bool_true;
}

static void enact_main_region_ADC_r1_DisplayData(Statechart* handle)
{
	/* Entry action for state 'DisplayData'. */
	statechart_displayInfo_ADC(handle);
	handle->completed = bool_true;
}

static void enact_main_region_ADC_r1_UsartTransmit_ADC(Statechart* handle)
{
	/* Entry action for state 'UsartTransmit_ADC'. */
	statechart_usartTransmit_ADC(handle);
	handle->completed = bool_true;
}

static void enact_main_region_ADC_r1_Tarpinis_RMS(Statechart* handle)
{
	/* Entry action for state 'Tarpinis_RMS'. */
	statechart_tarpinis_RMS(handle);
	handle->completed = bool_true;
}

static void enact_main_region_ADC_r1_ProcessData_ADC(Statechart* handle)
{
	/* Entry action for state 'ProcessData_ADC'. */
	statechart_processDataADC(handle);
	handle->completed = bool_true;
}

static void enact_main_region_I2C_r2_DisplayData(Statechart* handle)
{
	/* Entry action for state 'DisplayData'. */
	statechart_displayInfo_I2C(handle);
	handle->completed = bool_true;
}

static void enact_main_region_I2C_r2_UsartTransmit_I2C(Statechart* handle)
{
	/* Entry action for state 'UsartTransmit_I2C'. */
	statechart_usartTransmit_I2C(handle);
	handle->completed = bool_true;
}

static void enact_main_region_I2C_r2_ProcessData_I2C(Statechart* handle)
{
	/* Entry action for state 'ProcessData_I2C'. */
	statechart_processDataI2C(handle);
	handle->completed = bool_true;
}

static void enact_main_region_I2C_r2_ReadI2C(Statechart* handle)
{
	/* Entry action for state 'ReadI2C'. */
	statechart_readI2CSensor(handle);
	statechart_saveI2CSample(handle,handle->internal.sample_i2c);
	statechart_internal_set_sample_i2c(handle, (handle->internal.sample_i2c + 1));
	handle->completed = bool_true;
}

/* Exit action for state 'SampleReadingADC'. */
static void exact_main_region_ADC_r1_SampleReadingADC(Statechart* handle)
{
	/* Exit action for state 'SampleReadingADC'. */
	statechart_saveADCSample(handle,handle->internal.sample_no);
	statechart_internal_set_sample_no(handle, (handle->internal.sample_no + 1));
}

/* Exit action for state 'DisplayData'. */
static void exact_main_region_ADC_r1_DisplayData(Statechart* handle)
{
	/* Exit action for state 'DisplayData'. */
	statechart_internal_set_n_ADC(handle, 0);
}

/* Exit action for state 'UsartTransmit_ADC'. */
static void exact_main_region_ADC_r1_UsartTransmit_ADC(Statechart* handle)
{
	/* Exit action for state 'UsartTransmit_ADC'. */
	statechart_save_UsartTransmit_ADC(handle,handle->internal.N_ADC);
	statechart_internal_set_n_ADC(handle, (handle->internal.N_ADC + 1));
}

/* Exit action for state 'Tarpinis_RMS'. */
static void exact_main_region_ADC_r1_Tarpinis_RMS(Statechart* handle)
{
	/* Exit action for state 'Tarpinis_RMS'. */
	statechart_save_tarpinis_RMS(handle,handle->internal.sample1_no);
	statechart_internal_set_sample1_no(handle, (handle->internal.sample1_no + 1));
	statechart_internal_set_sample_no(handle, 0);
}

/* Exit action for state 'ProcessData_ADC'. */
static void exact_main_region_ADC_r1_ProcessData_ADC(Statechart* handle)
{
	/* Exit action for state 'ProcessData_ADC'. */
	statechart_internal_set_sample1_no(handle, 0);
}

/* Exit action for state 'DisplayData'. */
static void exact_main_region_I2C_r2_DisplayData(Statechart* handle)
{
	/* Exit action for state 'DisplayData'. */
	statechart_internal_set_n_I2C(handle, 0);
}

/* Exit action for state 'UsartTransmit_I2C'. */
static void exact_main_region_I2C_r2_UsartTransmit_I2C(Statechart* handle)
{
	/* Exit action for state 'UsartTransmit_I2C'. */
	statechart_save_UsartTransmit_I2C(handle,handle->internal.N_I2C);
	statechart_internal_set_n_I2C(handle, (handle->internal.N_I2C + 1));
}

/* Exit action for state 'ProcessData_I2C'. */
static void exact_main_region_I2C_r2_ProcessData_I2C(Statechart* handle)
{
	/* Exit action for state 'ProcessData_I2C'. */
	statechart_internal_set_sample_i2c(handle, 0);
}

/* 'default' enter sequence for state ADC */
static void enseq_main_region_ADC_default(Statechart* handle)
{
	/* 'default' enter sequence for state ADC */
	enseq_main_region_ADC_r1_default(handle);
}

/* 'default' enter sequence for state WaitSamplePeriod */
static void enseq_main_region_ADC_r1_WaitSamplePeriod_default(Statechart* handle)
{
	/* 'default' enter sequence for state WaitSamplePeriod */
	handle->stateConfVector[0] = Statechart_main_region_ADC_r1_WaitSamplePeriod;
}

/* 'default' enter sequence for state SampleRequestedADC */
static void enseq_main_region_ADC_r1_SampleRequestedADC_default(Statechart* handle)
{
	/* 'default' enter sequence for state SampleRequestedADC */
	enact_main_region_ADC_r1_SampleRequestedADC(handle);
	handle->stateConfVector[0] = Statechart_main_region_ADC_r1_SampleRequestedADC;
}

/* 'default' enter sequence for state SampleReadingADC */
static void enseq_main_region_ADC_r1_SampleReadingADC_default(Statechart* handle)
{
	/* 'default' enter sequence for state SampleReadingADC */
	enact_main_region_ADC_r1_SampleReadingADC(handle);
	handle->stateConfVector[0] = Statechart_main_region_ADC_r1_SampleReadingADC;
}

/* 'default' enter sequence for state DisplayData */
static void enseq_main_region_ADC_r1_DisplayData_default(Statechart* handle)
{
	/* 'default' enter sequence for state DisplayData */
	enact_main_region_ADC_r1_DisplayData(handle);
	handle->stateConfVector[0] = Statechart_main_region_ADC_r1_DisplayData;
}

/* 'default' enter sequence for state Tarpinis_RMS */
static void enseq_main_region_ADC_r1_Tarpinis_RMS_default(Statechart* handle)
{
	/* 'default' enter sequence for state Tarpinis_RMS */
	enact_main_region_ADC_r1_Tarpinis_RMS(handle);
	handle->stateConfVector[0] = Statechart_main_region_ADC_r1_Tarpinis_RMS;
}

/* 'default' enter sequence for state ProcessData_ADC */
static void enseq_main_region_ADC_r1_ProcessData_ADC_default(Statechart* handle)
{
	/* 'default' enter sequence for state ProcessData_ADC */
	enact_main_region_ADC_r1_ProcessData_ADC(handle);
	handle->stateConfVector[0] = Statechart_main_region_ADC_r1_ProcessData_ADC;
}

/* 'default' enter sequence for state I2C */
static void enseq_main_region_I2C_default(Statechart* handle)
{
	/* 'default' enter sequence for state I2C */
	enseq_main_region_I2C_r2_default(handle);
}

/* 'default' enter sequence for state WaitSamplePeriod */
static void enseq_main_region_I2C_r2_WaitSamplePeriod_default(Statechart* handle)
{
	/* 'default' enter sequence for state WaitSamplePeriod */
	handle->stateConfVector[0] = Statechart_main_region_I2C_r2_WaitSamplePeriod;
}

/* 'default' enter sequence for state DisplayData */
static void enseq_main_region_I2C_r2_DisplayData_default(Statechart* handle)
{
	/* 'default' enter sequence for state DisplayData */
	enact_main_region_I2C_r2_DisplayData(handle);
	handle->stateConfVector[0] = Statechart_main_region_I2C_r2_DisplayData;
}

/* 'default' enter sequence for state ProcessData_I2C */
static void enseq_main_region_I2C_r2_ProcessData_I2C_default(Statechart* handle)
{
	/* 'default' enter sequence for state ProcessData_I2C */
	enact_main_region_I2C_r2_ProcessData_I2C(handle);
	handle->stateConfVector[0] = Statechart_main_region_I2C_r2_ProcessData_I2C;
}

/* 'default' enter sequence for state ReadI2C */
static void enseq_main_region_I2C_r2_ReadI2C_default(Statechart* handle)
{
	/* 'default' enter sequence for state ReadI2C */
	enact_main_region_I2C_r2_ReadI2C(handle);
	handle->stateConfVector[0] = Statechart_main_region_I2C_r2_ReadI2C;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Statechart* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* 'default' enter sequence for region r1 */
static void enseq_main_region_ADC_r1_default(Statechart* handle)
{
	/* 'default' enter sequence for region r1 */
	react_main_region_ADC_r1__entry_Default(handle);
}

/* 'default' enter sequence for region r2 */
static void enseq_main_region_I2C_r2_default(Statechart* handle)
{
	/* 'default' enter sequence for region r2 */
	react_main_region_I2C_r2__entry_Default(handle);
}

/* Default exit sequence for state ADC */
static void exseq_main_region_ADC(Statechart* handle)
{
	/* Default exit sequence for state ADC */
	exseq_main_region_ADC_r1(handle);
}

/* Default exit sequence for state WaitSamplePeriod */
static void exseq_main_region_ADC_r1_WaitSamplePeriod(Statechart* handle)
{
	/* Default exit sequence for state WaitSamplePeriod */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state SampleRequestedADC */
static void exseq_main_region_ADC_r1_SampleRequestedADC(Statechart* handle)
{
	/* Default exit sequence for state SampleRequestedADC */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state SampleReadingADC */
static void exseq_main_region_ADC_r1_SampleReadingADC(Statechart* handle)
{
	/* Default exit sequence for state SampleReadingADC */
	handle->stateConfVector[0] = Statechart_last_state;
	exact_main_region_ADC_r1_SampleReadingADC(handle);
}

/* Default exit sequence for state DisplayData */
static void exseq_main_region_ADC_r1_DisplayData(Statechart* handle)
{
	/* Default exit sequence for state DisplayData */
	handle->stateConfVector[0] = Statechart_last_state;
	exact_main_region_ADC_r1_DisplayData(handle);
}

/* Default exit sequence for state UsartTransmit_ADC */
static void exseq_main_region_ADC_r1_UsartTransmit_ADC(Statechart* handle)
{
	/* Default exit sequence for state UsartTransmit_ADC */
	handle->stateConfVector[0] = Statechart_last_state;
	exact_main_region_ADC_r1_UsartTransmit_ADC(handle);
}

/* Default exit sequence for state Tarpinis_RMS */
static void exseq_main_region_ADC_r1_Tarpinis_RMS(Statechart* handle)
{
	/* Default exit sequence for state Tarpinis_RMS */
	handle->stateConfVector[0] = Statechart_last_state;
	exact_main_region_ADC_r1_Tarpinis_RMS(handle);
}

/* Default exit sequence for state ProcessData_ADC */
static void exseq_main_region_ADC_r1_ProcessData_ADC(Statechart* handle)
{
	/* Default exit sequence for state ProcessData_ADC */
	handle->stateConfVector[0] = Statechart_last_state;
	exact_main_region_ADC_r1_ProcessData_ADC(handle);
}

/* Default exit sequence for state I2C */
static void exseq_main_region_I2C(Statechart* handle)
{
	/* Default exit sequence for state I2C */
	exseq_main_region_I2C_r2(handle);
}

/* Default exit sequence for state WaitSamplePeriod */
static void exseq_main_region_I2C_r2_WaitSamplePeriod(Statechart* handle)
{
	/* Default exit sequence for state WaitSamplePeriod */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state DisplayData */
static void exseq_main_region_I2C_r2_DisplayData(Statechart* handle)
{
	/* Default exit sequence for state DisplayData */
	handle->stateConfVector[0] = Statechart_last_state;
	exact_main_region_I2C_r2_DisplayData(handle);
}

/* Default exit sequence for state UsartTransmit_I2C */
static void exseq_main_region_I2C_r2_UsartTransmit_I2C(Statechart* handle)
{
	/* Default exit sequence for state UsartTransmit_I2C */
	handle->stateConfVector[0] = Statechart_last_state;
	exact_main_region_I2C_r2_UsartTransmit_I2C(handle);
}

/* Default exit sequence for state ProcessData_I2C */
static void exseq_main_region_I2C_r2_ProcessData_I2C(Statechart* handle)
{
	/* Default exit sequence for state ProcessData_I2C */
	handle->stateConfVector[0] = Statechart_last_state;
	exact_main_region_I2C_r2_ProcessData_I2C(handle);
}

/* Default exit sequence for state ReadI2C */
static void exseq_main_region_I2C_r2_ReadI2C(Statechart* handle)
{
	/* Default exit sequence for state ReadI2C */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for region main region */
static void exseq_main_region(Statechart* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of Statechart.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_ADC_r1_WaitSamplePeriod :
		{
			exseq_main_region_ADC_r1_WaitSamplePeriod(handle);
			break;
		}
		case Statechart_main_region_ADC_r1_SampleRequestedADC :
		{
			exseq_main_region_ADC_r1_SampleRequestedADC(handle);
			break;
		}
		case Statechart_main_region_ADC_r1_SampleReadingADC :
		{
			exseq_main_region_ADC_r1_SampleReadingADC(handle);
			break;
		}
		case Statechart_main_region_ADC_r1_DisplayData :
		{
			exseq_main_region_ADC_r1_DisplayData(handle);
			break;
		}
		case Statechart_main_region_ADC_r1_UsartTransmit_ADC :
		{
			exseq_main_region_ADC_r1_UsartTransmit_ADC(handle);
			break;
		}
		case Statechart_main_region_ADC_r1_Tarpinis_RMS :
		{
			exseq_main_region_ADC_r1_Tarpinis_RMS(handle);
			break;
		}
		case Statechart_main_region_ADC_r1_ProcessData_ADC :
		{
			exseq_main_region_ADC_r1_ProcessData_ADC(handle);
			break;
		}
		case Statechart_main_region_I2C_r2_WaitSamplePeriod :
		{
			exseq_main_region_I2C_r2_WaitSamplePeriod(handle);
			break;
		}
		case Statechart_main_region_I2C_r2_DisplayData :
		{
			exseq_main_region_I2C_r2_DisplayData(handle);
			break;
		}
		case Statechart_main_region_I2C_r2_UsartTransmit_I2C :
		{
			exseq_main_region_I2C_r2_UsartTransmit_I2C(handle);
			break;
		}
		case Statechart_main_region_I2C_r2_ProcessData_I2C :
		{
			exseq_main_region_I2C_r2_ProcessData_I2C(handle);
			break;
		}
		case Statechart_main_region_I2C_r2_ReadI2C :
		{
			exseq_main_region_I2C_r2_ReadI2C(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default exit sequence for region r1 */
static void exseq_main_region_ADC_r1(Statechart* handle)
{
	/* Default exit sequence for region r1 */
	/* Handle exit of all possible states (of Statechart.main_region.ADC.r1) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_ADC_r1_WaitSamplePeriod :
		{
			exseq_main_region_ADC_r1_WaitSamplePeriod(handle);
			break;
		}
		case Statechart_main_region_ADC_r1_SampleRequestedADC :
		{
			exseq_main_region_ADC_r1_SampleRequestedADC(handle);
			break;
		}
		case Statechart_main_region_ADC_r1_SampleReadingADC :
		{
			exseq_main_region_ADC_r1_SampleReadingADC(handle);
			break;
		}
		case Statechart_main_region_ADC_r1_DisplayData :
		{
			exseq_main_region_ADC_r1_DisplayData(handle);
			break;
		}
		case Statechart_main_region_ADC_r1_UsartTransmit_ADC :
		{
			exseq_main_region_ADC_r1_UsartTransmit_ADC(handle);
			break;
		}
		case Statechart_main_region_ADC_r1_Tarpinis_RMS :
		{
			exseq_main_region_ADC_r1_Tarpinis_RMS(handle);
			break;
		}
		case Statechart_main_region_ADC_r1_ProcessData_ADC :
		{
			exseq_main_region_ADC_r1_ProcessData_ADC(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default exit sequence for region r2 */
static void exseq_main_region_I2C_r2(Statechart* handle)
{
	/* Default exit sequence for region r2 */
	/* Handle exit of all possible states (of Statechart.main_region.I2C.r2) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_I2C_r2_WaitSamplePeriod :
		{
			exseq_main_region_I2C_r2_WaitSamplePeriod(handle);
			break;
		}
		case Statechart_main_region_I2C_r2_DisplayData :
		{
			exseq_main_region_I2C_r2_DisplayData(handle);
			break;
		}
		case Statechart_main_region_I2C_r2_UsartTransmit_I2C :
		{
			exseq_main_region_I2C_r2_UsartTransmit_I2C(handle);
			break;
		}
		case Statechart_main_region_I2C_r2_ProcessData_I2C :
		{
			exseq_main_region_I2C_r2_ProcessData_I2C(handle);
			break;
		}
		case Statechart_main_region_I2C_r2_ReadI2C :
		{
			exseq_main_region_I2C_r2_ReadI2C(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_ADC_default(handle);
}

/* Default react sequence for initial entry  */
static void react_main_region_ADC_r1__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_ADC_r1_WaitSamplePeriod_default(handle);
}

/* Default react sequence for initial entry  */
static void react_main_region_I2C_r2__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_I2C_r2_WaitSamplePeriod_default(handle);
}


static sc_integer react(Statechart* handle, const sc_integer transitioned_before)
{
	/* State machine reactions. */
	SC_UNUSED(handle);
	return transitioned_before;
}

static sc_integer main_region_ADC_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state ADC. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->iface.ButtonPush_raised == bool_true)
			{ 
				exseq_main_region_ADC(handle);
				enseq_main_region_I2C_default(handle);
				react(handle,0);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = react(handle,transitioned_before);
		} 
	} return transitioned_after;
}

static sc_integer main_region_ADC_r1_WaitSamplePeriod_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state WaitSamplePeriod. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->iface.Ev_GetSample_raised == bool_true)
			{ 
				exseq_main_region_ADC_r1_WaitSamplePeriod(handle);
				enseq_main_region_ADC_r1_SampleRequestedADC_default(handle);
				main_region_ADC_react(handle,0);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = main_region_ADC_react(handle,transitioned_before);
		} 
	} return transitioned_after;
}

static sc_integer main_region_ADC_r1_SampleRequestedADC_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state SampleRequestedADC. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->iface.Ev_ADCSampleReady_raised == bool_true)
			{ 
				exseq_main_region_ADC_r1_SampleRequestedADC(handle);
				enseq_main_region_ADC_r1_SampleReadingADC_default(handle);
				main_region_ADC_react(handle,0);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = main_region_ADC_react(handle,transitioned_before);
		} 
	} return transitioned_after;
}

static sc_integer main_region_ADC_r1_SampleReadingADC_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state SampleReadingADC. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state SampleReadingADC */
		handle->stateConfVector[0] = Statechart_last_state;
		exact_main_region_ADC_r1_SampleReadingADC(handle);
		/* The reactions of state null. */
		if ((handle->internal.sample_no) == (500))
		{ 
			enseq_main_region_ADC_r1_Tarpinis_RMS_default(handle);
		}  else
		{
			enseq_main_region_ADC_r1_WaitSamplePeriod_default(handle);
		}
	}  else
	{
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = main_region_ADC_react(handle,transitioned_before);
		} 
	}
	return transitioned_after;
}

static sc_integer main_region_ADC_r1_DisplayData_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state DisplayData. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state DisplayData */
		handle->stateConfVector[0] = Statechart_last_state;
		exact_main_region_ADC_r1_DisplayData(handle);
		/* 'default' enter sequence for state WaitSamplePeriod */
		handle->stateConfVector[0] = Statechart_main_region_ADC_r1_WaitSamplePeriod;
		main_region_ADC_react(handle,0);
	}  else
	{
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = main_region_ADC_react(handle,transitioned_before);
		} 
	}
	return transitioned_after;
}

static sc_integer main_region_ADC_r1_UsartTransmit_ADC_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state UsartTransmit_ADC. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state UsartTransmit_ADC */
		handle->stateConfVector[0] = Statechart_last_state;
		exact_main_region_ADC_r1_UsartTransmit_ADC(handle);
		/* The reactions of state null. */
		if ((handle->internal.N_ADC) == (2))
		{ 
			enseq_main_region_ADC_r1_DisplayData_default(handle);
		}  else
		{
			enseq_main_region_ADC_r1_WaitSamplePeriod_default(handle);
		}
	}  else
	{
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = main_region_ADC_react(handle,transitioned_before);
		} 
	}
	return transitioned_after;
}

static sc_integer main_region_ADC_r1_Tarpinis_RMS_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Tarpinis_RMS. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state Tarpinis_RMS */
		handle->stateConfVector[0] = Statechart_last_state;
		exact_main_region_ADC_r1_Tarpinis_RMS(handle);
		/* The reactions of state null. */
		if ((handle->internal.sample1_no) == (10))
		{ 
			enseq_main_region_ADC_r1_ProcessData_ADC_default(handle);
		}  else
		{
			enseq_main_region_ADC_r1_WaitSamplePeriod_default(handle);
		}
	}  else
	{
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = main_region_ADC_react(handle,transitioned_before);
		} 
	}
	return transitioned_after;
}

static sc_integer main_region_ADC_r1_ProcessData_ADC_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state ProcessData_ADC. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state ProcessData_ADC */
		handle->stateConfVector[0] = Statechart_last_state;
		exact_main_region_ADC_r1_ProcessData_ADC(handle);
		/* 'default' enter sequence for state UsartTransmit_ADC */
		enact_main_region_ADC_r1_UsartTransmit_ADC(handle);
		handle->stateConfVector[0] = Statechart_main_region_ADC_r1_UsartTransmit_ADC;
		main_region_ADC_react(handle,0);
	}  else
	{
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = main_region_ADC_react(handle,transitioned_before);
		} 
	}
	return transitioned_after;
}

static sc_integer main_region_I2C_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state I2C. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->iface.ButtonPush_raised == bool_true)
			{ 
				exseq_main_region_I2C(handle);
				enseq_main_region_ADC_default(handle);
				react(handle,0);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = react(handle,transitioned_before);
		} 
	} return transitioned_after;
}

static sc_integer main_region_I2C_r2_WaitSamplePeriod_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state WaitSamplePeriod. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->iface.Ev_GetSample_i2c_raised == bool_true)
			{ 
				exseq_main_region_I2C_r2_WaitSamplePeriod(handle);
				enseq_main_region_I2C_r2_ReadI2C_default(handle);
				main_region_I2C_react(handle,0);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = main_region_I2C_react(handle,transitioned_before);
		} 
	} return transitioned_after;
}

static sc_integer main_region_I2C_r2_DisplayData_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state DisplayData. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state DisplayData */
		handle->stateConfVector[0] = Statechart_last_state;
		exact_main_region_I2C_r2_DisplayData(handle);
		/* 'default' enter sequence for state WaitSamplePeriod */
		handle->stateConfVector[0] = Statechart_main_region_I2C_r2_WaitSamplePeriod;
		main_region_I2C_react(handle,0);
	}  else
	{
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = main_region_I2C_react(handle,transitioned_before);
		} 
	}
	return transitioned_after;
}

static sc_integer main_region_I2C_r2_UsartTransmit_I2C_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state UsartTransmit_I2C. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state UsartTransmit_I2C */
		handle->stateConfVector[0] = Statechart_last_state;
		exact_main_region_I2C_r2_UsartTransmit_I2C(handle);
		/* The reactions of state null. */
		if ((handle->internal.N_I2C) == (30))
		{ 
			enseq_main_region_I2C_r2_DisplayData_default(handle);
		}  else
		{
			enseq_main_region_I2C_r2_WaitSamplePeriod_default(handle);
		}
	}  else
	{
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = main_region_I2C_react(handle,transitioned_before);
		} 
	}
	return transitioned_after;
}

static sc_integer main_region_I2C_r2_ProcessData_I2C_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state ProcessData_I2C. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state ProcessData_I2C */
		handle->stateConfVector[0] = Statechart_last_state;
		exact_main_region_I2C_r2_ProcessData_I2C(handle);
		/* 'default' enter sequence for state UsartTransmit_I2C */
		enact_main_region_I2C_r2_UsartTransmit_I2C(handle);
		handle->stateConfVector[0] = Statechart_main_region_I2C_r2_UsartTransmit_I2C;
		main_region_I2C_react(handle,0);
	}  else
	{
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = main_region_I2C_react(handle,transitioned_before);
		} 
	}
	return transitioned_after;
}

static sc_integer main_region_I2C_r2_ReadI2C_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state ReadI2C. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state ReadI2C */
		handle->stateConfVector[0] = Statechart_last_state;
		/* The reactions of state null. */
		if ((handle->internal.sample_i2c) == (80))
		{ 
			enseq_main_region_I2C_r2_ProcessData_I2C_default(handle);
		}  else
		{
			enseq_main_region_I2C_r2_WaitSamplePeriod_default(handle);
		}
	}  else
	{
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = main_region_I2C_react(handle,transitioned_before);
		} 
	}
	return transitioned_after;
}




static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq)
{
	return eq->size;
}

static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq)
{
	statechart_event event;
	if(statechart_eventqueue_size(eq) <= 0) {
		statechart_event_init(&event, Statechart_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev)
{
	if(statechart_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void statechart_event_init(statechart_event * ev, StatechartEventID name)
{
	ev->name = name;
}

static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name)
{
	statechart_event event;
	statechart_event_init(&event, name);
	statechart_eventqueue_push(eq, event);
}

static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event) {
	switch(event->name) {
		case Statechart_Ev_GetSample:
		{
			handle->iface.Ev_GetSample_raised = bool_true;
			return bool_true;
		}
		case Statechart_Ev_ADCSampleReady:
		{
			handle->iface.Ev_ADCSampleReady_raised = bool_true;
			return bool_true;
		}
		case Statechart_Ev_GetSample_i2c:
		{
			handle->iface.Ev_GetSample_i2c_raised = bool_true;
			return bool_true;
		}
		case Statechart_ButtonPush:
		{
			handle->iface.ButtonPush_raised = bool_true;
			return bool_true;
		}
		default:
			return bool_false;
	}
}

static statechart_event statechart_get_next_event(Statechart* handle)
{
	statechart_event next_event;
	statechart_event_init(&next_event, Statechart_invalid_event);
	if(statechart_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = statechart_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static sc_boolean statechart_dispatch_next_event(Statechart* handle)
{
	statechart_event nextEvent;
	nextEvent = statechart_get_next_event(handle);
	return statechart_dispatch_event(handle, &nextEvent);
}
